[phases.setup]
nixPkgs = ['nodejs_18', 'npm']

[phases.install]
cmds = ['npm ci']

[phases.build]
cmds = ['echo "Node.js steganography service ready"']

[start]
cmd = 'npm start'

[variables]
NODE_ENV = 'production' 